#define DOMAIN_SERVERS_PATH	"/usr/lib/cosmosfs/dpserver"
#define RQL_MODULE_PATH		"/usr/lib/cosmosfs/rql"
#define DPAK_INDEX_PATH		"/var/lib/cosmosfs/dp"
#define AXPA_INDEX_PATH		"/var/lib/cosmosfs/ax"
#define RQSTR_INDEX_PATH	"/var/lib/cosmosfs/rq"
#define SCANLIB_DB_PATH		"/var/lib/cosmosfs/ss"
